# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smart Hashtags' do
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~>  4.7.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smart Hashtags

end
